---
- hosts: [Host group name]
  name: Copy Wazuh agent msi file and Install on remote machine
  gather_facts: true
  become_method: runas
  tasks:
    - name: Copy Wazuh-Agent msi file
      win_copy:
        src: [Path of msi on ansible server]
        dest: [Path of msi on Host machine]

    - name: Install Wazuh-Agent on remote machine
      win_package:
        path: [Path of msi on Host machine]
        arguments: '/q WAZUH_MANAGER="[Wazuh Server IP]"'

    - name: Execute cmd command for start wazuh agent service
      win_command:
        NET START WazuhSvc
        become_method: runas

    - name: Delete msi file
      win_package:
        path: [Path of msi on ansible Host]
        status: absent
        become_method: runas