---
- name: Disable Untrusted Macro Execution
  hosts: all

  tasks:
    - name: Set registry value to disable Untrusted Macro Execution in Excel
      win_regedit:
        path: HKCU:\Software\Microsoft\Office\16\Excel\Security
        name: VBAWarnings
        data: 4
        datatype: dword
        state: present
      become_method: runas
      register: reg_change_result
    - name: Set registry value to disable Untrusted Macro Execution in Word
      win_regedit:
        path: HKCU:\Software\Microsoft\Office\16\Word\Security
        name: VBAWarnings
        data: 4
        datatype: dword
        state: present
      become_method: runas
      register: reg_change_result
    - name: Set registry value to disable Untrusted Macro Execution in PowerPoint
      win_regedit:
        path: HKCU:\Software\Microsoft\Office\16\PowerPoint\Security
        name: VBAWarnings
        data: 4
        datatype: dword
        state: present
      become_method: runas
      register: reg_change_result

    - name: Refresh group policy settings
      win_command: gpupdate /force
      become_method: runas
    - name: Check if registry value was changed
      debug:
        var: reg_change_result.changed