---
- name: WinVerifyTrust Signature Validation CVE-2013-3900 Mitigation (EnableCertPaddingCheck)
  hosts: all
  gather_facts: false
  tasks:
    - name: Add Registry Key
      win_regedit:
        path: HKLM:\Software\Microsoft\Cryptography\Wintrust\config
        state: present
      register: Key_Added
    - name: Add Registry Key
      win_regedit:
        path: HKLM:\Software\Wow6432Node\Microsoft\Cryptography\Wintrust\Config
        state: present
      register: Key_Added

    - name: Set registry value to EnableCertPaddingCheck
      win_regedit:
        path: HKLM:\Software\Microsoft\Cryptography\Wintrust\config
        name: EnableCertPaddingCheck
        data: 1
        datatype: string
        state: present
      register: reg_change_result
    - name: Set registry value to EnableCertPaddingCheck
      win_regedit:
        path: HKLM:\Software\Wow6432Node\Microsoft\Cryptography\Wintrust\Config
        name: EnableCertPaddingCheck
        data: 1
        datatype: string
        state: present
      become_method: runas
      register: reg_change_result
    - name: Refresh group policy settings
      win_command: gpupdate /force
      become_method: runas